[package]
name = "Rust-text-editor_meow_"
version = "3.1416"
edition = "2025"

[[bin]]
name = "meow"
path = "src/main.rs"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
unicode-width = "0.1"
arboard = "3.4"
