background = "#212733"
foreground = "#d9d7ce"
cursor = "#ffcc66"
selection_bg = "#343f4c"
status_bg = "#ffcc66"
status_fg = "#212733"
keyword = "#ffa759"
string = "#bae67e"
comment = "#5c6773"
number = "#d4bfff"
