background = "#eff1f5"
foreground = "#4c4f69"
cursor = "#dc8a78"
selection_bg = "#ccd0da"
status_bg = "#ea76cb"
status_fg = "#eff1f5"
keyword = "#8839ef"
string = "#40a02b"
comment = "#9ca0b0"
number = "#fe640b"
