background = "#282a36"
foreground = "#f8f8f2"
cursor = "#aeafad"
selection_bg = "#44475a"
status_bg = "#6272a4"
status_fg = "#f8f8f2"
keyword = "#ff79c6"
string = "#f1fa8c"
comment = "#6272a4"
number = "#bd93f9"
