background = "#fbf1c7"
foreground = "#3c3836"
cursor = "#3c3836"
selection_bg = "#ebdbb2"
status_bg = "#b57614"
status_fg = "#fbf1c7"
keyword = "#9d0006"
string = "#79740e"
comment = "#928374"
number = "#8f3f71"
