background = "#282828"
foreground = "#ebdbb2"
cursor = "#ebdbb2"
selection_bg = "#3c3836"
status_bg = "#fabd2f"
status_fg = "#282828"
keyword = "#fb4934"
string = "#b8bb26"
comment = "#928374"
number = "#d3869b"
