background = "#272822"
foreground = "#f8f8f2"
cursor = "#f8f8f2"
selection_bg = "#49483e"
status_bg = "#a6e22e"
status_fg = "#272822"
keyword = "#f92672"
string = "#e6db74"
comment = "#75715e"
number = "#ae81ff"
