background = "#2e3440"
foreground = "#d8dee9"
cursor = "#d8dee9"
selection_bg = "#4c566a"
status_bg = "#81a1c1"
status_fg = "#2e3440"
keyword = "#81a1c1"
string = "#a3be8c"
comment = "#4c566a"
number = "#b48ead"
