background = "#282c34"
foreground = "#abb2bf"
cursor = "#528bff"
selection_bg = "#3e4451"
status_bg = "#61afef"
status_fg = "#282c34"
keyword = "#c678dd"
string = "#98c379"
comment = "#5c6370"
number = "#d19a66"
