background = "#002b36"
foreground = "#839496"
cursor = "#93a1a1"
selection_bg = "#073642"
status_bg = "#268bd2"
status_fg = "#002b36"
keyword = "#859900"
string = "#2aa198"
comment = "#586e75"
number = "#d33682"
