background = "#fdf6e3"
foreground = "#657b83"
cursor = "#586e75"
selection_bg = "#eee8d5"
status_bg = "#268bd2"
status_fg = "#fdf6e3"
keyword = "#859900"
string = "#2aa198"
comment = "#93a1a1"
number = "#d33682"
