[editor]
tab_size = 4
line_numbers = true
mouse_support = true
theme = "nord" # See available themes below

[theme]
# (Optional) Overrides for specific colors if "theme" is set to "default" or left empty.
background = "#282c34"
foreground = "#abb2bf"
cursor = "#528bff"
selection_bg = "#3e4451"
